-- MySQL Script generated by MySQL Workbench
-- Mon May  6 09:55:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema efcc_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema efcc_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `efcc_db` DEFAULT CHARACTER SET latin1 ;
USE `efcc_db` ;

-- -----------------------------------------------------
-- Table `efcc_db`.`petition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efcc_db`.`petition` (
  `casefile_no` VARCHAR(50) NOT NULL,
  `cr_no` VARCHAR(50) NOT NULL,
  `date_received` DATETIME NOT NULL,
  `date_assigned` DATETIME NOT NULL,
  `amount_involved` INT(11) NULL DEFAULT NULL,
  `status_signal` ENUM('Convicted', 'In-Progress') NULL DEFAULT NULL,
  `petition_source` ENUM('Intelligence', 'Regular-Complain') NULL DEFAULT NULL,
  PRIMARY KEY (`casefile_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `efcc_db`.`complainant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efcc_db`.`complainant` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `address` VARCHAR(128) NOT NULL,
  `nationality` VARCHAR(20) NOT NULL,
  `state` ENUM('Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara') NOT NULL,
  `gender` ENUM('Male', 'Female') NOT NULL,
  `age` SMALLINT(6) NOT NULL,
  `occupation` VARCHAR(50) NOT NULL,
  `religion` ENUM('Islam', 'Christianity', 'Traditional', 'Others') NOT NULL,
  `education` ENUM('Primary', 'Secondary', 'Tertiary') NOT NULL,
  `phone_no` VARCHAR(15) NOT NULL,
  `petition_no` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `petition_no` (`petition_no` ASC) VISIBLE,
  CONSTRAINT `complainant_ibfk_1`
    FOREIGN KEY (`petition_no`)
    REFERENCES `efcc_db`.`petition` (`casefile_no`))
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `efcc_db`.`suspect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efcc_db`.`suspect` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `height` SMALLINT(6) NOT NULL,
  `skin_color` ENUM('Dark Brown', 'Brown', 'Light Brown', 'Dark', 'Fair', 'Caramel') NULL DEFAULT NULL,
  `passport` BLOB NOT NULL,
  `mugshot` BLOB NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `nationality` VARCHAR(20) NULL DEFAULT NULL,
  `place_of_birth` VARCHAR(50) NOT NULL,
  `gender` ENUM('Male', 'Female') NOT NULL,
  `religion` ENUM('Islam', 'Christianity', 'Traditional', 'Others') NOT NULL,
  `occupation` VARCHAR(50) NOT NULL,
  `phone_no` VARCHAR(15) NOT NULL,
  `parent_name` VARCHAR(50) NOT NULL,
  `petition_no` VARCHAR(50) NULL DEFAULT NULL,
  `complainant_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `petition_no` (`petition_no` ASC) VISIBLE,
  INDEX `complainant_id` (`complainant_id` ASC) VISIBLE,
  CONSTRAINT `suspect_ibfk_1`
    FOREIGN KEY (`petition_no`)
    REFERENCES `efcc_db`.`petition` (`casefile_no`),
  CONSTRAINT `suspect_ibfk_2`
    FOREIGN KEY (`complainant_id`)
    REFERENCES `efcc_db`.`complainant` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `efcc_db`.`recovery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efcc_db`.`recovery` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `petition_no` VARCHAR(50) NULL DEFAULT NULL,
  `suspects` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `petition_no` (`petition_no` ASC) VISIBLE,
  INDEX `suspects` (`suspects` ASC) VISIBLE,
  CONSTRAINT `recovery_ibfk_1`
    FOREIGN KEY (`petition_no`)
    REFERENCES `efcc_db`.`petition` (`casefile_no`),
  CONSTRAINT `recovery_ibfk_2`
    FOREIGN KEY (`suspects`)
    REFERENCES `efcc_db`.`suspect` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `efcc_db`.`automobile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efcc_db`.`automobile` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `plate_number` VARCHAR(10) NULL DEFAULT NULL,
  `chasis_number` VARCHAR(50) NULL DEFAULT NULL,
  `colar` VARCHAR(20) NULL DEFAULT NULL,
  `other_info` VARCHAR(128) NULL DEFAULT NULL,
  `status` ENUM('With Exhibit keeper', 'Tendered in Court', 'Interim forfeiture', 'Final Forfeiture') NOT NULL,
  `recovery_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `recovery_id` (`recovery_id` ASC) VISIBLE,
  CONSTRAINT `automobile_ibfk_1`
    FOREIGN KEY (`recovery_id`)
    REFERENCES `efcc_db`.`recovery` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `efcc_db`.`monetary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efcc_db`.`monetary` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` ENUM('With Exhibit keeper', 'Tendered in Court', 'Interim forfeiture', 'Final Forfeiture') NOT NULL,
  `recovery_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `recovery_id` (`recovery_id` ASC) VISIBLE,
  CONSTRAINT `monetary_ibfk_1`
    FOREIGN KEY (`recovery_id`)
    REFERENCES `efcc_db`.`recovery` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `efcc_db`.`bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efcc_db`.`bank` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `bank_name` VARCHAR(50) NULL DEFAULT NULL,
  `serial_number` INT(11) NULL DEFAULT NULL,
  `amount` INT(11) NULL DEFAULT NULL,
  `favour_off` VARCHAR(20) NULL DEFAULT NULL,
  `monetary_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `monetary_id` (`monetary_id` ASC) VISIBLE,
  CONSTRAINT `bank_ibfk_1`
    FOREIGN KEY (`monetary_id`)
    REFERENCES `efcc_db`.`monetary` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `efcc_db`.`crypto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efcc_db`.`crypto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `asset_name` VARCHAR(50) NULL DEFAULT NULL,
  `asset_size` VARCHAR(50) NULL DEFAULT NULL,
  `asset_worth` INT(11) NULL DEFAULT NULL,
  `monetary_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `monetary_id` (`monetary_id` ASC) VISIBLE,
  CONSTRAINT `crypto_ibfk_1`
    FOREIGN KEY (`monetary_id`)
    REFERENCES `efcc_db`.`monetary` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `efcc_db`.`electronic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efcc_db`.`electronic` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` ENUM('With Exhibit keeper', 'Tendered in Court', 'Interim forfeiture', 'Final Forfeiture') NOT NULL,
  `recovery_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `recovery_id` (`recovery_id` ASC) VISIBLE,
  CONSTRAINT `electronic_ibfk_1`
    FOREIGN KEY (`recovery_id`)
    REFERENCES `efcc_db`.`recovery` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `efcc_db`.`fingerprint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efcc_db`.`fingerprint` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `finger_print` VARCHAR(128) NULL DEFAULT NULL,
  `mugshot` BLOB NULL DEFAULT NULL,
  `petition_no` VARCHAR(50) NULL DEFAULT NULL,
  `suspects` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `petition_no` (`petition_no` ASC) VISIBLE,
  INDEX `suspects` (`suspects` ASC) VISIBLE,
  CONSTRAINT `fingerprint_ibfk_1`
    FOREIGN KEY (`petition_no`)
    REFERENCES `efcc_db`.`petition` (`casefile_no`),
  CONSTRAINT `fingerprint_ibfk_2`
    FOREIGN KEY (`suspects`)
    REFERENCES `efcc_db`.`suspect` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `efcc_db`.`identity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efcc_db`.`identity` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_types` ENUM('Licence', 'NIN', 'Passport') NOT NULL,
  `id_number` VARCHAR(50) NOT NULL,
  `susp_id` INT(11) NULL DEFAULT NULL,
  `petition_no` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `susp_id` (`susp_id` ASC) VISIBLE,
  INDEX `petition_no` (`petition_no` ASC) VISIBLE,
  CONSTRAINT `identity_ibfk_1`
    FOREIGN KEY (`susp_id`)
    REFERENCES `efcc_db`.`suspect` (`id`),
  CONSTRAINT `identity_ibfk_2`
    FOREIGN KEY (`petition_no`)
    REFERENCES `efcc_db`.`petition` (`casefile_no`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `efcc_db`.`jewelry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efcc_db`.`jewelry` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(128) NULL DEFAULT NULL,
  `status` ENUM('With Exhibit keeper', 'Tendered in Court', 'Interim forfeiture', 'Final Forfeiture') NOT NULL,
  `recovery_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `recovery_id` (`recovery_id` ASC) VISIBLE,
  CONSTRAINT `jewelry_ibfk_1`
    FOREIGN KEY (`recovery_id`)
    REFERENCES `efcc_db`.`recovery` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `efcc_db`.`landedproperty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efcc_db`.`landedproperty` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(50) NOT NULL,
  `size` INT(11) NULL DEFAULT NULL,
  `status` ENUM('With Exhibit keeper', 'Tendered in Court', 'Interim forfeiture', 'Final Forfeiture') NOT NULL,
  `recovery_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `recovery_id` (`recovery_id` ASC) VISIBLE,
  CONSTRAINT `landedproperty_ibfk_1`
    FOREIGN KEY (`recovery_id`)
    REFERENCES `efcc_db`.`recovery` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `efcc_db`.`laptop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efcc_db`.`laptop` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `serial_no` VARCHAR(50) NOT NULL,
  `color` VARCHAR(20) NULL DEFAULT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `electronic_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `electronic_id` (`electronic_id` ASC) VISIBLE,
  CONSTRAINT `laptop_ibfk_1`
    FOREIGN KEY (`electronic_id`)
    REFERENCES `efcc_db`.`electronic` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `efcc_db`.`other`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efcc_db`.`other` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(128) NULL DEFAULT NULL,
  `electronic_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `electronic_id` (`electronic_id` ASC) VISIBLE,
  CONSTRAINT `other_ibfk_1`
    FOREIGN KEY (`electronic_id`)
    REFERENCES `efcc_db`.`electronic` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `efcc_db`.`phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `efcc_db`.`phone` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `phone_name` VARCHAR(50) NOT NULL,
  `color` VARCHAR(20) NULL DEFAULT NULL,
  `imei` VARCHAR(50) NULL DEFAULT NULL,
  `electronic_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `electronic_id` (`electronic_id` ASC) VISIBLE,
  CONSTRAINT `phone_ibfk_1`
    FOREIGN KEY (`electronic_id`)
    REFERENCES `efcc_db`.`electronic` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
